### ISSUE TITLE
Parameter for overwriting schema.php

### ISSUE THREAD

**Issue by ravage84** [CakeDC/migrations#220]
Since I'm using a VCS, I do no tneed to generate schema snapshots.
Because of this I always choose overwriting the schema.php.
It would be nice if there was a parameter to this, e.g. ``--overwrite`` or ``-o``.

So instead of executing ``console\cake.bat Migrations.migration generate -f``  (on Windows) and then have to answer a question I know the answer to already, I would execute ``console\cake.bat Migrations.migration generate -f -o``. This would help me to DRY.

This makes especially sense if you prepare such commands in your IDE or in a automation tool, such as ANT.

Related Shell code:
https://github.com/CakeDC/migrations/blob/2.4.0/Console/Command/MigrationShell.php#L448-L453

**Comment by ravage84** [comment]
Related: https://github.com/CakeDC/migrations/issues/221

**Comment by ravage84** [comment]
@omnuvito what is the reason for the issue close?

**Comment by omnuvito** [comment]
Hi Mark, this issue was resolved and merged in develop, the option to overwrite a schema is available in this branch.

-- 
José Alejandro Alvarez Mendoza
Developer
Cake Development Corporation
Attention: José Alejandro Alvarez Mendoza

1785 East Sahara Avenue, Suite 490-423
Las Vegas, Nevada 89104
Phone: +1 702 60 50 400


http://www.cakedc.com

On November 3, 2015 at 09:31:21, Marc Würth (notifications@github.com) wrote:

@omnuvito what is the reason for the issue close?

—
Reply to this email directly or view it on GitHub.


-- 
This email may contain material that is confidential, privileged and/or 
work product for the sole use of the intended recipient.  Any review, 
reliance or distribution by others or forwarding without express permission 
is strictly prohibited.  If you are not the intended recipient, please 
contact the sender and delete all copies.

Cake Development Corporation.

**Comment by ravage84** [comment]
OH OK, thanks for the feedback.
Funny, I can't find any related change/commit.

**Comment by omnuvito** [comment]
Hi @ravage84, sorry for the misunderstanding, the parameter to overwrite scheme file is now available in develop branch.
