### ISSUE TITLE
Plugin not detecting foreign keys

### ISSUE THREAD

**Issue by lucas-nadalutti** [CakeDC/migrations#230]
I'm using the migrations plugin to migrate DB changes to Amazon's RDS service. It works fine except for the fact that it doesn't seem to add FK constraints to the RDS's tables. Having a look at the generated migration's file, I'm almost sure that the issue happens when generating it (sorry, had a hard time trying to format this without success, but I think it's understandable).

public $migration = array(
	    'up' => array(
			'alter_field' => array(
				'attractions_hotels' => array(
					'hotel_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'unsigned' => true, 'key' => 'index'),
				),
			),
			'create_field' => array(
				'attractions_hotels' => array(
					'indexes' => array(
						'hotel_id' => array('column' => 'hotel_id', 'unique' => 0),
					),
				),
			),
		),
		'down' => array(
			'alter_field' => array(
				'attractions_hotels' => array(
					'hotel_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'unsigned' => true),
				),
			),
			'drop_field' => array(
				'attractions_hotels' => array('indexes' => array('hotel_id')),
			),
		),
	);

This is the migration in which I generate the foreign keys, with the ON DELETE CASCADE constraint. As you can see, the migration does not seem to consider the foreign keys. I am using the InnoDB engine both locally and in the RDS instance, and the FK constraints work locally (i.e. when I delete a `hotel`, every related record in `attractions_hotels` is also deleted).

Sorry if this is a known issue, I couldn't find anything related. I also apologize if I'm missing something.

**Comment by LenzLueers** [comment]
I ran into the same issue using a Cake 2 application interacting with a postgreSQL database. The migration plugin ignores foreign key associations and converts my existing constraints (using cascading) into indexes, which do not support the "on"-clause.

I guess the reason is that Cakes' approach is to handle the referential integrity itself by using the model associations (dependent attribute and cascade option for delete operation). So from a cake point of view there is no real need to use the database layer for that. I personally prefer to guarantee the referential integrity on the lowest level possible, but that does not seem to be completely possible with the migration plugin at this point.

Since I still have several Cake2 projects to maintain, I'd love to see this feature in the migrations plugin as well, but I don't know, if it is still maintained, for Cake 3 switched to phinx as migration-service. 

Any news from the core developer team on that matter?

**Comment by steinkel** [comment]
Docs were updated saying that foreign key constraints are not supported. Thanks!
